import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/ui/header";
import { ThemeProvider } from "./components/ui/theme-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoMono = Geist_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const inter = Geist({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
        ${geistSans.variable} 
        ${robotoMono.variable} 
        ${inter.variable} 
        ${geistMono.variable} 
        antialiased 
        flex
        min-h-screen
        min-w-full
        `
        }

      >
        <ThemeProvider
          attribute="class"       // Переключать через класс 'dark'
          defaultTheme="system"
          enableSystem
        >
          <Header />
          <div className="flex-1 min-w-auto">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
