import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import Header from "@/app/components/ui/header";
import { ThemeProvider } from "./components/ui/theme-provider";
import { cn } from "@/lib/utils";
import { SessionProviderWrapper } from "./components/sessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", GeistSans.variable)}>
      <body
        className={cn(
          GeistSans.variable,
          GeistMono.variable,
          "antialiased min-h-screen bg-background text-foreground"
        )}
      >
        <SessionProviderWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            {/* Фиксированный сайдбар */}
            <Header />

            {/* Основной контент - сдвинут вправо */}
            <main className="ml-20 min-h-screen transition-all duration-300 ease-in-out ">
              <div className="w-full">
                {children}
              </div>
            </main>

          </ThemeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}